# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop
  - main

pr:
  - develop
  - main

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: vars/prod.yml
- ${{ else }}:
  - template: vars/nprod.yml

pool: Services-Pool

stages:
- stage: Test
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - deployment: RundeckProjectsJobs
    displayName: Rundeck Projects & Jobs
    environment:
      name: $(az_devops_environment)
      resourceType: virtualMachine
      tags: primary
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: Terraform Validate
            inputs:
              targetType: 'inline'
              script: |
                terraform init -upgrade
                terraform validate
              bashEnvValue: '/etc/profile'
          - task: Bash@3
            displayName: Terraform Plan
            inputs:
              filePath: 'scripts/terraform_plan_apply.sh'
              arguments: 'plan $(environment)'
              bashEnvValue: '/etc/profile'
            env:
              TF_IN_AUTOMATION: true
              TF_VAR_rundeck_url: $(rundeck_url)
              TF_VAR_rundeck_token: $(rundeck_token)
              TF_VAR_rundeck_hosts: $(rundeck_hosts)
              TF_VAR_rundeck_hosts_user: $(rundeck_hosts_user)
              TF_VAR_rundeck_hosts_password: $(rundeck_hosts_password)
- stage: Build
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: GetRequirementsFiles
    displayName: Get Ansible Requirements
    steps:
    - task: Bash@3
      name: Galaxy
      displayName: Ansible-Galaxy Install
      inputs:
        targetType: 'inline'
        bashEnvValue: '/etc/profile'
        script: |
          rm -rf $(Build.SourcesDirectory)/.ansible 2> /dev/null
          find ./projects/ -maxdepth 2 -regex '.*requirements.ya?ml' | while read requirements_file
          do
            echo "##vso[task.setvariable variable=hasRequirements;isOutput=true]true"
            source $(Agent.HomeDirectory)/venv/bin/activate
            ansible-galaxy install -r $requirements_file
          done
      env:
        ANSIBLE_ROLES_PATH: $(Build.SourcesDirectory)/.ansible/roles
        ANSIBLE_COLLECTIONS_PATHS: $(Build.SourcesDirectory)/.ansible/collections
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.SourcesDirectory)/.ansible/
        ArtifactName: ansible-galaxy-requirements
        publishLocation: 'Container'
        StoreAsTar: true
- stage: Deploy
  dependsOn: Build
  condition: in(dependencies.Build.result, 'Succeeded', 'SucceededWithIssues')
  jobs:
  - deployment: RundeckAnsibleRequirements
    displayName: Rundeck Ansible Requirements
    environment:
      name: $(az_devops_environment)
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: Extract Ansible Requirements
            inputs:
              targetType: 'inline'
              bashEnvValue: '/etc/profile'
              script: |
                ansible_requirements=$(Pipeline.Workspace)/ansible-galaxy-requirements/ansible-galaxy-requirements.tar
                sudo su rundeck -c "tar -xvf $ansible_requirements -C /var/lib/rundeck/.ansible"
  - deployment: RundeckProjectsJobs
    displayName: Rundeck Projects & Jobs
    environment:
      name: $(az_devops_environment)
      resourceType: virtualMachine
      tags: primary
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: Terraform Apply
            inputs:
              filePath: 'scripts/terraform_plan_apply.sh'
              arguments: 'apply $(environment)'
              bashEnvValue: '/etc/profile'
            env:
              TF_IN_AUTOMATION: true
              TF_VAR_rundeck_url: $(rundeck_url)
              TF_VAR_rundeck_token: $(rundeck_token)
              TF_VAR_rundeck_hosts: $(rundeck_hosts)
              TF_VAR_rundeck_hosts_user: $(rundeck_hosts_user)
              TF_VAR_rundeck_hosts_password: $(rundeck_hosts_password)
- stage: Report
  condition: failed()
  jobs:
  - job: AzureBoardsBugCard
    displayName: Azure Boards Bug Card
    steps:
    - checkout: none
    - task: CreateWorkItem@1
      displayName: Azure Boards Create Bug Card
      inputs:
        teamProject: My_Team_Project
        areaPath: 'My_Team_Project\Q1'
        iterationPath: 'itration_path_uuid@currentIteration'
        workItemType: bug
        title: 'Terraform-Rundeck: Pipeline Error'
        fieldMappings: |
          Description = Error while executing <strong>[infra] Terraform-Rundeck-CD pipeline:</strong> <br />https://dev.azure.com/My_Team_Project/_build/results?buildId=$(Build.BuildId)&view=results
          Product = Automation
